### ISSUE TITLE
oef-Error

### ISSUE THREAD

**Issue by Exolas** [felixlinker/FUPS#12]
23:28:18 Bad conversion: array
23:28:18 Error in expression <breakOut _fnc_scriptname;
};
};
} count nearestObjects [_pos,[],20];

false>
23:28:18   Error position: <nearestObjects [_pos,[],20];

false>
23:28:18   Error 0 elements provided, 3 expected
23:28:18 File C:\Users\NixName\Documents\Arma 3 - Other Profiles\Exolas\missions\[GrpW]_Co05_SealEcho_1v0.Chernarus\FUPS\functions\map\fn_inForest.sqf, line 12

23:28:18 Error in expression <_lastQuery"];
_revealVal = _revealVal - linearConversion [FUPS_targeting_forgetT>
23:28:18   Error position: <linearConversion [FUPS_targeting_forgetT>
23:28:18   Error Type Number,Not a Number, expected Number
23:28:18 File C:\Users\NixName\Documents\Arma 3 - Other Profiles\Exolas\missions\[GrpW]_Co05_SealEcho_1v0.Chernarus\FUPS\functions\targeting\fn_targeting_getThreshold.sqf, line 5

23:28:18 Error in expression <targeting_maxRange) exitWith {0};

if !(lineIntersectsSurfaces [getPosASL _lookF>
23:28:18   Error position: <lineIntersectsSurfaces [getPosASL _lookF>
23:28:18   Error 0 elements provided, 3 expected
23:28:18 File C:\Users\NixName\Documents\Arma 3 - Other Profiles\Exolas\missions\[GrpW]_Co05_SealEcho_1v0.Chernarus\FUPS\functions\targeting\fn_targeting_getChance.sqf, line 8

**Comment by felixlinker** [comment]
Nächster commit müsste das fixen. Da scheint ein falscher Parameter übergeben worden zu sein, an sich lässt sich aber kein Fehler im Code finden.

**Comment by felixlinker** [comment]
Da der Fehler nicht erneut gemeldet wurde, schließe ich den Issue.
