### ISSUE TITLE
mainHandler.sqf, line 338

### ISSUE THREAD

**Issue by Exolas** [felixlinker/FUPS#14]
20:35:01 Error in expression << 1 - _skipActionChance) then {
_params call (missionnamespace getVariable _task>
20:35:01   Error position: <call (missionnamespace getVariable _task>
20:35:01   Error call: Type Object, expected code
20:35:01 File mpmissions\__CUR_MP.Takistan\FUPS\functions\fn_mainHandler.sqf, line 338

**Comment by felixlinker** [comment]
Da der Fehler nicht erneut gemeldet wurde, ist er wahrscheinlich behoben.
