### ISSUE TITLE
Strange behaviour on enemy contact

### ISSUE THREAD

**Issue by felixlinker** [felixlinker/FUPS#20]
AI lays down and moves very slowly. Contributed by @GitHawk

**Comment by GitHawk** [comment]
In der heutigen Mission `Sahrani Breakdown` hat sich wohl lt. Ironbrizz ein Squad auf den Boden gelegt und nicht mehr bewegt.

**Comment by felixlinker** [comment]
This issue will no longer be supervised since FUPS gets a complete overhaul.
