### ISSUE TITLE
fn_randomMarkerPos

### ISSUE THREAD

**Issue by Exolas** [felixlinker/FUPS#5]
Zeile 15: Du versuchst zwar den Fall _pos isEqualTo [] abzufangen, allerdings kommt dennoch ein Fehler, da "distance" ein Array mit drei Werten erwartet. Eine lazy evaluation könnte da Abhilfe schaffen.
Ich bin jetzt allerdings auf den Fall gestoßen (mir ist noch nicht ganz klar wie), dass in den 10000 Durchläufen die "while" im scheduled enviroment hat, keine Position gefunden wurde. Das führt einerseits zu einem kurzzeitigen Freeze von etwa drei Sekunden und andererseits zu weiteren Fehlern in "fn_generateWP" und "fn_task_patrol", da logischerweise ein leeres Array als _randomPos der Rückgabewert ist. (nur mit der nicht-Dev Version getestet)

**Comment by Exolas** [comment]
In meinem spezifischen Fall scheint der Fehler dadurch zu entstehen, dass gespawnte RHS T80U patrouillieren sollen, nachdem sie gespawnt sind. Nach entfernen der Panzer aus den Spawnbefehlen kommen keine Fehler mehr.

**Comment by felixlinker** [comment]
Wird gefixt
