### ISSUE TITLE
Ein paar Fehlerchen

### ISSUE THREAD

**Issue by Exolas** [felixlinker/FUPS#6]
Ich hab leider gerad nicht die Zeit mich genauer damit auseinander zu setzen, daher hier die Fehler die momentan die Server-RPT´s in die Luft sprengen:

22:40:34 Error in expression <typeName";
if !(isNil {missionnamespace getVariable (_task + _typeName)}) then {>
22:40:34   Error position: <getVariable (_task + _typeName)}) then {>
22:40:34   Error getvariable: Type Number,Not a Number, expected Array,String
22:40:34 File mpmissions\__cur_mp.clafghan\FUPS\functions\fn_mainHandler.sqf, line 350

22:40:20 Error in expression <p] call FUPS_fnc_g_weapons;

_g_weapons select _ai_type
>
22:40:20   Error position: <select _ai_type
>
22:40:20   Error Zero divisor
22:40:20 File mpmissions\__cur_mp.clafghan\FUPS\functions\information\fn_fears.sqf, line 22

Und noch einer von Draider der ebenfalls oEF vorkam:

15:55:26 Error in expression <iable "FUPS_movePos";
if (leader _group distance _pos < (_group getVariable "FUP>
15:55:26   Error position: <distance _pos < (_group getVariable "FUP>
15:55:26   Error 0 elements provided, 3 expected
15:55:26 File C:\Users\hp\Documents\Arma 3 - Other Profiles\Draider\missions\[GrpW]_Co+32_Dieselkrieg.Takistan\FUPS\functions\tasks\patrol\fn_task_patrol.sqf, line 37

**Comment by felixlinker** [comment]
Keine Ahnung, woher der erste Fehler kommt. Das ist eigentlich unmöglich, da die Variable nur einmal geschrieben und sonst gelesen wird.
Ich hatte den Fehler aber schon mal im Zusammenhang mit Fahrzeugen.
Ich fange den Fehler jetzt explizit ab und schmeiße eine Fehlermeldung, wenn er auftritt. Dadurch sollte es zu keinen Crashes kommen, aber wir können ihn weiter verfolgen.

**Comment by felixlinker** [comment]
Der Fehler in der fn_fears.sqf wird auch abgefangen, da kann ich nicht mehr machen. Ich brauche den reproduziert.

**Comment by felixlinker** [comment]
Der dritte Fehler könnte mit einem anderen commit gelöst sein.
