### ISSUE TITLE
Destroy-Wegpunkt

### ISSUE THREAD

**Issue by Exolas** [felixlinker/FUPS#7]
Die RPT des Server bekommt neuerdings

16:03:59 Destroy waypoint not linked to a target: Near target acquisition is slow and may even select friendly unit.

in 10.000-facher Ausführung reingedrückt. https://forums.bistudio.com/topic/177389-destroy-waypoint-not-linked-to-a-target/ könnte eine Antwort bieten, allerdings kann ich momentan nicht sagen, ob der Fehler überhaupt von FUPS oder einem Missionsbauer kommt.

**Comment by felixlinker** [comment]
Fehler kommt nicht von FUPS, da ich nicht mit (direkt) Wegpunkten arbeite.
