### ISSUE TITLE
fn_randomMarkerPos die Zweite

### ISSUE THREAD

**Issue by Exolas** [felixlinker/FUPS#8]
18:43:44 Error in expression <[]) && _waterCondition && leader _group distance _pos > _mindist) then {
_random>
18:43:44   Error position: <distance _pos > _mindist) then {
_random>
18:43:44   Error 0 elements provided, 3 expected
18:43:44 File C:\Users\NixName\Documents\Arma 3 - Other Profiles\Exolas\missions\[GrpW]_Co05_SealEcho_1v0.Chernarus\FUPS\functions\map\fn_randomMarkerPos.sqf, line 15

**Comment by felixlinker** [comment]
Lazy evaluation vergessen, wird gefixt.
